### ISSUE TITLE
README badge broken

### ISSUE THREAD

**Issue by kotx** [RainwayApp/bebop#135]
Small issue, but yeah
![image](https://user-images.githubusercontent.com/33439542/126576500-39c52181-8e02-4a33-a72c-8609628b7217.png)

**Comment by kotx** [comment]
@bengreenier This doesn't seem to be fully resolved- The "REPL Build" badge is broken, and the logo doesn't look nice on dark theme:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/33439542/144934287-33be9e6d-2d6f-458c-bb17-2969129ec6c3.png">

For images for dark theme, GitHub recently released a feature for that: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by bengreenier** [comment]
@kotx Unfortunately the badges are dependent on shields.io right now, because our workflows aren't named clearly, and GitHub doesn't support name changes as part of their workflow badges, it seems. 

Perhaps you are experiencing this issue they mention:

> If your GitHub badge errors, it might be because you hit GitHub's rate limits. 

I do see them rendering just fine for me:

![image](https://user-images.githubusercontent.com/1167891/144934908-a9edbe93-7c6f-4da3-a712-9d746ee7d5bf.png)

We currently only have a dark icon for bebop, and creating a light version wasn't in scope i'm afraid. I personally don't think it looks too bad, but maybe we can find time to make a lighter version in the future - Thanks for that feedback and link!
