### ISSUE TITLE
Variable-length integer encoding

### ISSUE THREAD

**Issue by davidsky** [RainwayApp/bebop#198]
**Is your feature request related to a problem? Please describe.**
Schemas with a many integers dramatically differ in size. Such size reduction will make Bebop also suitable to use as a long term storage format. 

**Describe the solution you'd like**
Variable-length integer instead of fixed length.

**Describe alternatives you've considered**
Using protobuf due to this issue, even though Bebop is clearly faster and easier to use.

**Comment by Eadword** [comment]
A large part of why bebop is so fast is because we don't do this. In Rust, for example, we don't even have to copy fixed-sized structs but can just point to where they are in the serialized data. We have talked a bit about ways to decrease the encoded size of bebop before but no encoding changes really make a lot of sense for us.

We use this in our company for very low-latency streaming, and so speed has to be the priority. For long-term storage or slightly more size-sensitive applications, I would recommend throwing the data through lz4, gzip, or really whatever you want depending on your size requirements. The added bonus of doing so is it will also potentially be able to compress your data itself and not just some of the excess zeros in the integers.
