### ISSUE TITLE
Clarification on byte vs uint8

### ISSUE THREAD

**Issue by 200sc** [RainwayApp/bebop#71]
Intuitively `byte == uint8`, however in [Writing Bops](https://github.com/RainwayApp/bebop/wiki/Writing-Bops:-The-Bebop-Schema-Language), `uint8` is not listed as a type, so its not allowed. So far so good. 

The [msgpack comparison example](https://github.com/RainwayApp/bebop/blob/master/Laboratory/Schemas/msgpack_comparison.bop) uses the `uint8` type: i.e. `uint8 iNT0; // "int0": 0,`.

Is `uint8` a valid builtin type? Is the example outdated? Do the docs just need a clarification `'byte' or 'uint8'`?

**Comment by AndrewMD5** [comment]
Bebop supports type aliases so you can use either byte or uint8 and both represent an unsigned 8-bit integer.

**Comment by 200sc** [comment]
So to bring this to resolution, should `uint8` be added to the Writing Bops guide? Or should a doc be written explaining type aliases (which I assume are a builtin only feature, in which case it would ideally list the built in aliases that exist)?

**Comment by 200sc** [comment]
For additional context, it looks like in the existing codebase the -only- type alias is `uint8 = byte` (https://github.com/RainwayApp/bebop/blob/8c65bcb1271168b67ea308ab52556e34c488fe66/Core/Parser/Extensions/TypeExtensions.cs#L16)

**Comment by lynn** [comment]
I updated the schema language documentation to note that `uint8` is an alias for `byte`.

**Comment by lynn** [comment]
There is another kind of alias-like behavior, where you can write either `array[T]` or `T[]` to name the “array of `T`” type. Indeed, `uint8` = `byte` is the only base type alias right now, and there is not yet any way to specify custom type aliases.

This alias exists because sometimes it makes sense to talk about bytes as “the smallest memory unit”, like when talking about a `byte[]`, but other times it makes sense to think about a byte as an “8-bit unsigned numeric type”, and in that case the name `uint8` is provided to match all the other ones.
