### ISSUE TITLE
Clarification on readonly messages

### ISSUE THREAD

**Issue by 200sc** [RainwayApp/bebop#74]
The bebop vscode extension reports `The 'readonly' modifer cannot be applied to 'MyMessage' as it is not a struct` when given `readonly message MyMessage`. 

Assuming this is intentional, what about messages disables them from being generated in a way that they are immutable to the consumer?

**Comment by AndrewMD5** [comment]
Correct this is intentional. Because a `message` is compromised of optional members it is expected that they will be modified to some degree, whether it is just setting something to `null` or some other runtime operation. Serialization is also more "complex" for a `message` since members have to be detected before their data is used.  For example, an instance of `MyMessage` will be created at the beginning of the decoding process, however it's individual members are set later individually based on their availability.

Because a `struct` guarantee that all its members are present with non-null values, serialization is much simpler. When a struct is marked readonly generated code can use built-in language features to ensure data is immutable after decoding. For example, generated C# code uses the `init` keyword on the property accessors, whereas TypeScript uses `readonly` on the interface member. 

The requirement of both those programming languages is that you initialize the objects either via a `.ctor` or an object initializer; we choose the latter. So the following struct

```bebop
readonly struct Point {
  uint32 X;
  uint32 Y;
}
```

Produces a decoding method that is fairly simple:
```csharp
 internal static Point DecodeFrom(ref BebopReader reader) {

      uint field0;
      field0 = reader.ReadUInt32();
      uint field1;
      field1 = reader.ReadUInt32();
      return new Point {
        X = field0,
        Y = field1,
      };
    }
```
whereas a `message` variant requires multiple loops to set values:

```csharp
internal static Point DecodeFrom(ref BebopReader reader) {

      var record = new Point();
      var length = reader.ReadRecordLength();
      var end = unchecked((int) (reader.Position + length));
      while (true) {
        switch (reader.ReadByte()) {
          case 0:
            return record;
          case 1:
            record.X = reader.ReadUInt32();
            break;
          case 2:
            record.Y = reader.ReadUInt32();
            break;
          default:
            reader.Position = end;
            return record;
        }
      }
    }
```

So if you need data to be immutable and you know it's always going to be present you should default to using a `readonly struct`.  If data is always present but can be modified a normal `struct` will suffice. If any member can be missing then you'll want to use a `message`.  A `readonly message` would break the contract a `message` represents -- highly mutable, dynamic data.

**Comment by 200sc** [comment]
Thank you for the info!
